# -*- coding: utf-8 -*-
"""Progetto_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzhWx5KlGekYiFWs36Ao27VNdCXW56z1

Il file “dataset_latin1.txt” ha le seguenti colonne:
- Nome
- Cognome
- Data di nascita
- Sesso
- Luogo di nascita

## PRIMA PARTE

Utilizza il dataset “dataset_latin1.txt” per rispondere alle seguenti domande:

- Quante sono le persone descritte nel file?
- Quante sono le persone di sesso maschile? Femminile?
- Individuate il cognome più diffuso e la sua numerosità (la numerosità delle - persone che hanno tale cognome)
- Individuate il nome più diffuso e la sua numerosità
- Individuate il comune di nascita più diffuso e la numerosità
"""

persone=[]
nome=[]
cognome=[]
data_nascita=[]
sesso=[]
luogo_nascita=[]

#ho specificato encoding perchè altrimenti mi causava errore
with open("dataset_latin1.txt","r", encoding="latin-1") as file:
  for case in file:
    case=case.strip()
    case=case.split('\n')
    persone.append(case)
    for i in case:
      i=i.strip()
      i=i.split(',')
      nome.append(i[0])
      cognome.append(i[1])
      data_nascita.append(i[2])
      sesso.append(i[3])
      luogo_nascita.append(i[4])

def valore_diffuso(lista):
  #creazione dizionario
  numerosità={}
  for value in lista:
    if value in numerosità:
      numerosità[value]+=1
    elif value not in numerosità:
      numerosità[value]=1
  # print("dizionario: \n",numerosità)

  # calcolo di sicurezza
  n=0
  valore_diffuso=[]
  max=0
  for i,value in numerosità.items():
    n+=value
    if value >= max:
      max=value
      valore_diffuso.append(i)
  print(f"calcolo sicurezza:{n==len(lista)} ",)

  return valore_diffuso

#comuni
comuni={}
with open('elenco_codici_comuni_latin1.txt','r', encoding="latin-1")as file:
  comuni_list=[]
  for C in file:
    C=C.strip()
    C=C.split(',')
    comuni_list.append(C)
  i=0
  while i<len(comuni_list):
    comuni[comuni_list[i][1]]=comuni_list[i][0]
    i+=1
  print(comuni)

"""##DOMANDE"""

#Quante sono le persone descritte nel file?
print(len(persone))

# Quante sono le persone di sesso maschile? Femminile?
m=0
f=0

for i in sesso:
  if i == 'M':
    m+=1
  else:
    f+=1
print(f"le persone di sesso maschile sono {m} invece di sesso femminile {f}")

print(m+f)

# Individuate il cognome più diffuso e la sua numerosità (la numerosità delle - persone che hanno tale cognome)
cognomi_diffusi=valore_diffuso(cognome)
print("i cognomi piu diffusi sono:\n",cognomi_diffusi)

# Individuate il nome più diffuso e la sua numerosità
nome_diffusi=valore_diffuso(nome)
print("i nomi piu diffusi sono:\n",nome_diffusi)

# Individuate il comune di nascita più diffuso e la numerosità
luogo_diffuso=valore_diffuso(luogo_nascita)
print("i luoghi  piu diffusi sono:\n",nome_diffusi)

"""##CODICE FISCALE

1. Codice del Cognome (3 lettere)

Si prendono le prime tre consonanti del cognome. Se ci sono meno di tre consonanti, si aggiungono le vocali nell'ordine in cui compaiono.
Se il cognome ha meno di tre lettere, si aggiunge la lettera "X" fino a completare il segmento.

Esempio: Per il cognome "Rossi" → "RSS". Per "Li" → "LIX".

2. Codice del Nome (3 lettere)

Si prendono le prime tre consonanti del nome.
Se il nome ha quattro o più consonanti, si selezionano la prima, la terza e la quarta consonante (saltando la seconda).
Se ci sono meno di tre consonanti, si aggiungono le vocali in ordine.

Esempio: Per il nome "Giovanni" → "GVN". Per "Lia" → "LIA".

3. Codice della Data di Nascita e del Sesso (5 caratteri)

Anno: Si prendono le ultime due cifre dell'anno di nascita.
Mese: Si usa una lettera per indicare il mese di nascita, secondo la seguente tabella:

Gennaio: A, Febbraio: B, Marzo: C, Aprile: D, Maggio: E, Giugno: H, Luglio: L, Agosto: M, Settembre: P, Ottobre: R, Novembre: S, Dicembre: T.

Giorno e Sesso: Per i maschi si usano i numeri del giorno di nascita così come sono, mentre per le femmine si aggiunge 40 al giorno di nascita.

Esempio: Una donna nata il 15 febbraio 1980 avrà il codice "80B55" (1980 → 80, Febbraio → B, Giorno 15+40 → 55).

4. Codice del Comune di Nascita (4 caratteri)

Ogni comune italiano ha un codice alfanumerico di quattro caratteri (come "H501" per Roma). Per chi è nato all'estero, esiste un codice specifico per lo stato di nascita (non tenerlo in considerazione in questo progetto).

Il file di testo “elenco_codici_comuni_latin1.txt” contiene l’elenco dei comuni italiani con i loro codici associati

5. Carattere di Controllo (1 carattere)

L’ultimo carattere è un carattere di controllo (o "check digit") calcolato sulla base dei 15 caratteri precedenti. Questo carattere di controllo serve a evitare errori di trascrizione.

Per questo progetto utilizzeremo il carattere ‘X’
"""

#dati
vocali=['A','E','I','O','U']
consonanti = ['B', 'C', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z']
mensile = {
    "01": "A",
    "02": "B",
    "03": "C",
    "04": "D",
    "05": "E",
    "06": "H",
    "07": "L",
    "08": "M",
    "09": "P",
    "10": "R",
    "11": "S",
    "12": "T"
}

def creazione_CF(nome,cognome,anno,sesso,luogo):
  cf=''
  #codice cognome
  if(len(cognome)<3):
    cf=cognome+'X'
  else:
    for lettera in cognome:
      if(lettera in consonanti):
        cf=cf+lettera

    if (len(cf)<3):
      for lettera in cognome:
        if(lettera in vocali and len(cf)<3):
          cf=cf+lettera

  #codice nome
  nome_consonante=[]
    #prendiamo tutte le consonanti e li inseriamo in una lista
  for lettera in nome:
    if(lettera in consonanti):
      nome_consonante.append(lettera)

  #vediamo se hanno  quattro o più consonanti  altrimenti inseriamo le consonanti insieme alle vocali
  if(len(nome_consonante)>=4):
    cf=cf+nome_consonante[0]+nome_consonante[2]+nome_consonante[3]
  else:
    tnome=''
    for l in nome_consonante:
      tnome=tnome+l

    for lettera in nome:
      if (lettera in vocali and len(tnome)<3):
        tnome=tnome+lettera
    cf=cf+tnome

  #data di nascita
  anno_list=[]
  tanno=''
  for i in anno:
    anno_list.append(i)
    # anno
  tanno=anno_list[4]+anno_list[5]
  cf=cf+tanno
    # mese
  tmese=anno_list[2]+anno_list[3]
  if tmese in mensile:
    cf=cf+mensile[tmese]

   #giorno
  tgiorno=anno_list[0]+anno_list[1]
  if(sesso =='M'):
    cf=cf+tgiorno
  else:
    tgiorno=int(tgiorno)+40
    tgiorno=str(tgiorno)
    cf=cf+tgiorno
  #comune di nascita

  if(luogo in comuni):
    cf=cf +comuni[luogo]

  # carattere di controllo
  cf=cf+'X'
  return cf

#inizio CF
cf_list=[]
i=0

while i<len(persone):
  cf_creato=creazione_CF(nome[i],cognome[i],data_nascita[i],sesso[i],luogo_nascita[i])
  cf_list.append(cf_creato)
  i+=1

print(cf_list)